# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a00498ea221818021ebb9b09627431e50cd10b08f1716e9237155b22dabc340db1005f01ef8569ca7c3f8f6c0d62513fef592534408bee7eea071cf2e64d49

test:
  secret_key_base: 57e584af8e0ee1e4a95a6c7e42cf94f166a0437eb206ca6c97e1ce0e39a0a6fc03bac69fd25f93266ea003429964ae2b751502da053eb2792405d3934b141fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
